
name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Build snake animation
    runs-on: ubuntu-latest
    steps:
      # 🧩 Gera a animação da cobrinha
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Mateus97lima
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=0affff
            dist/github-contribution-grid-snake-light.svg?palette=github-light&color_snake=0078ff

      # 📤 Publica no branch "output"
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
